# 用于搭建测试环境

version: "3"

services:
  swc-redis:
    image: "redis:alpine"
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6379:6379"

  swc-mongo:
    image: "mongo:4.4.4-bionic"
    environment:
      TZ: Asia/Shanghai
    ports:
      - "27018:27017"
    volumes:
      - /Your/Absolute/Path:/data/db

  video-analysis:
    build:
      context: ./video_analysis
    environment:
      TZ: Asia/Shanghai
    ports:
      - "50051:50051"
    volumes:
      - /Your/Absolute/Path/swc-log/:/swc/log/
      - /Your/Absolute/Path/swc-backend/video_analysis/:/swc/code/video_analysis/
      - /Your/Absolute/Path/swc-resource/:/swc/resource/

  api-server:
    build: .
    ports:
      - "6666:8080"
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - swc-redis
      - swc-mongo
      - video-analysis
    volumes:
      - /Your/Absolute/Path/swc-backend/:/swc/code/
      - /Your/Absolute/Path/swc-resource/:/swc/resource/
      - /Your/Absolute/Path/swc-log/:/swc/log/
