version: "3"

services:
  video-analysis:
    build:
      context: ./video_analysis
      cache_from:
        - video-analysis:v1
    ports:
      - "50051:50051"

  api-server:
    build: .
    ports:
      - "6666:8080"
    depends_on:
      - video-analysis
