// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: server/network/videoanalysis.proto

package network

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type VideoInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// job的唯一ID
	JobID string `protobuf:"bytes,1,opt,name=job_iD,json=jobID,proto3" json:"job_iD,omitempty"`
	// 视频文件路径
	File string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	// 静态视频摘要（图片）的保存目录，需确保该目录已经存在
	SaveDir string `protobuf:"bytes,3,opt,name=save_dir,json=saveDir,proto3" json:"save_dir,omitempty"`
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_network_videoanalysis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_network_videoanalysis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_server_network_videoanalysis_proto_rawDescGZIP(), []int{0}
}

func (x *VideoInfo) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

func (x *VideoInfo) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *VideoInfo) GetSaveDir() string {
	if x != nil {
		return x.SaveDir
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// job的唯一ID
	JobID string `protobuf:"bytes,1,opt,name=job_iD,json=jobID,proto3" json:"job_iD,omitempty"`
	// 静态视频摘要文件名列表
	PicName []string `protobuf:"bytes,2,rep,name=pic_name,json=picName,proto3" json:"pic_name,omitempty"`
	// 错误信息
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_network_videoanalysis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_server_network_videoanalysis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_server_network_videoanalysis_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

func (x *Result) GetPicName() []string {
	if x != nil {
		return x.PicName
	}
	return nil
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_server_network_videoanalysis_proto protoreflect.FileDescriptor

var file_server_network_videoanalysis_proto_rawDesc = []byte{
	0x0a, 0x22, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a, 0x09, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x73, 0x61, 0x76, 0x65, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x61, 0x76, 0x65, 0x44, 0x69, 0x72, 0x22, 0x50, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x44, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x69, 0x63, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x70, 0x69, 0x63, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x40, 0x0a, 0x0d, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12, 0x2f, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x41, 0x62, 0x73, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x12, 0x0a, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f,
	0x1a, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x73,
	0x77, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_network_videoanalysis_proto_rawDescOnce sync.Once
	file_server_network_videoanalysis_proto_rawDescData = file_server_network_videoanalysis_proto_rawDesc
)

func file_server_network_videoanalysis_proto_rawDescGZIP() []byte {
	file_server_network_videoanalysis_proto_rawDescOnce.Do(func() {
		file_server_network_videoanalysis_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_network_videoanalysis_proto_rawDescData)
	})
	return file_server_network_videoanalysis_proto_rawDescData
}

var file_server_network_videoanalysis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_network_videoanalysis_proto_goTypes = []interface{}{
	(*VideoInfo)(nil), // 0: VideoInfo
	(*Result)(nil),    // 1: Result
}
var file_server_network_videoanalysis_proto_depIdxs = []int32{
	0, // 0: VideoAnalysis.GetStaticVideoAbstract:input_type -> VideoInfo
	1, // 1: VideoAnalysis.GetStaticVideoAbstract:output_type -> Result
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_network_videoanalysis_proto_init() }
func file_server_network_videoanalysis_proto_init() {
	if File_server_network_videoanalysis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_network_videoanalysis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_network_videoanalysis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_network_videoanalysis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_network_videoanalysis_proto_goTypes,
		DependencyIndexes: file_server_network_videoanalysis_proto_depIdxs,
		MessageInfos:      file_server_network_videoanalysis_proto_msgTypes,
	}.Build()
	File_server_network_videoanalysis_proto = out.File
	file_server_network_videoanalysis_proto_rawDesc = nil
	file_server_network_videoanalysis_proto_goTypes = nil
	file_server_network_videoanalysis_proto_depIdxs = nil
}
