# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import video_pb2 as video__pb2


class VideoAnalysisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStaticVideoAbstract = channel.unary_unary(
                '/VideoAnalysis/GetStaticVideoAbstract',
                request_serializer=video__pb2.VideoInfo.SerializeToString,
                response_deserializer=video__pb2.Result.FromString,
                )


class VideoAnalysisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStaticVideoAbstract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoAnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStaticVideoAbstract': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStaticVideoAbstract,
                    request_deserializer=video__pb2.VideoInfo.FromString,
                    response_serializer=video__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VideoAnalysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoAnalysis(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStaticVideoAbstract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/VideoAnalysis/GetStaticVideoAbstract',
            video__pb2.VideoInfo.SerializeToString,
            video__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
